name: Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - website/**

permissions:
  pull-requests: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Deploy
        uses: the-guild-org/shared-config/website-cf@main
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: graphql-education
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: ./website
          buildScript: yarn build
          artifactDir: ./dist
